apiVersion: apps/v1
kind: Deployment
metadata:
  name: kci-server
  namespace: kci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kci-server
  template:
    metadata:
      labels:
        app: kci-server
    spec:
      containers:
      - name: kci-server
        image: patnaikshekhar/kci-server
        env:
        - name: PS_EXPECTED_HOSTNAME
          value: kci.shekharpatnaik.com
        ports:
        - containerPort: 10000
          name: grpc
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: ./certs
        - name: config
          mountPath: /.kci
      serviceAccountName: kci-server
      volumes:
      - name: certs
        secret:
          secretName: kci-server-secret
      - name: config
        configMap:
          name: kci-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kci-server
  namespace: kci
data:
  config.yaml: |
    url: localhost:10000
    cert: /certs/server.crt
