apiVersion: v1
kind: Namespace
metadata:
  name: kci
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kci-server
  namespace: kci
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kci-server
  namespace: kci
rules:
- apiGroups: [""]
  verbs: ["list", "get"]
  resources: ["pods/logs", "pods", "secrets"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  metadata:
    name: kci-server-binding
    namespace: kci
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: kci-server
subjects:
- kind: ServiceAccount
  name: kci-server
  namespace: kci
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kci-server
  namespace: kci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kci-server
  template:
    metadata:
      labels:
        app: kci-server
    spec:
      containers:
      - name: kci-server
        image: patnaikshekhar/kci-server:1
        containerPort:
        - port: 10000
          name: grpc
      serviceAccountName: kci
---

apiVersion: v1
kind: Service
metadata:
  name: kci-server
  namespace: kci
spec:
  selector:
    app: kci-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 10000
  
  
