// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package kci

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Steps                []*Step  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *BuildRequest) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Step struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Step) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type BuildResponse struct {
	Update               string   `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "kci.BuildRequest")
	proto.RegisterType((*Step)(nil), "kci.Step")
	proto.RegisterType((*BuildResponse)(nil), "kci.BuildResponse")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcf, 0xce, 0x82, 0x30,
	0x10, 0xc4, 0xc3, 0xc7, 0x9f, 0x84, 0xfd, 0xf4, 0xe0, 0xc6, 0x18, 0xe2, 0x41, 0x09, 0x17, 0x39,
	0x35, 0x06, 0xe3, 0x0b, 0x78, 0xf5, 0x60, 0x52, 0x9f, 0xa0, 0x40, 0x43, 0x1a, 0x84, 0xd6, 0xb6,
	0x1c, 0x7c, 0x7b, 0x03, 0xc5, 0x84, 0xdb, 0xce, 0x2f, 0x3b, 0xb3, 0xb3, 0x00, 0x1d, 0x13, 0x3d,
	0x51, 0x5a, 0x5a, 0x89, 0x7e, 0x5b, 0x89, 0xec, 0x01, 0xab, 0xdb, 0x20, 0x5e, 0x35, 0xe5, 0xef,
	0x81, 0x1b, 0x8b, 0x07, 0x00, 0xcd, 0x95, 0x34, 0xc2, 0x4a, 0xfd, 0x49, 0xbc, 0xd4, 0xcb, 0x63,
	0xba, 0x20, 0x78, 0x84, 0xd0, 0x58, 0xae, 0x4c, 0xf2, 0x97, 0xfa, 0xf9, 0x7f, 0x11, 0x93, 0xb6,
	0x12, 0xe4, 0x69, 0xb9, 0xa2, 0x8e, 0x67, 0x67, 0x08, 0x46, 0x89, 0x5b, 0x08, 0x45, 0xc7, 0x1a,
	0x3e, 0x67, 0x38, 0x81, 0x08, 0x01, 0xd3, 0x8d, 0x73, 0xc7, 0x74, 0x9a, 0xb3, 0x13, 0xac, 0xe7,
	0x0a, 0x46, 0xc9, 0xde, 0x70, 0xdc, 0x41, 0x34, 0xa8, 0x9a, 0xd9, 0x9f, 0x77, 0x56, 0xc5, 0x15,
	0xfc, 0x7b, 0x25, 0x90, 0x40, 0x58, 0x8e, 0xfb, 0xb8, 0x99, 0x8e, 0x2f, 0xeb, 0xef, 0x71, 0x89,
	0x5c, 0x5c, 0x19, 0x4d, 0xef, 0x5e, 0xbe, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xbc, 0xef, 0x15,
	0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KciClient is the client API for Kci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KciClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type kciClient struct {
	cc *grpc.ClientConn
}

func NewKciClient(cc *grpc.ClientConn) KciClient {
	return &kciClient{cc}
}

func (c *kciClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, "/kci.Kci/build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KciServer is the server API for Kci service.
type KciServer interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
}

// UnimplementedKciServer can be embedded to have forward compatible implementations.
type UnimplementedKciServer struct {
}

func (*UnimplementedKciServer) Build(ctx context.Context, req *BuildRequest) (*BuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}

func RegisterKciServer(s *grpc.Server, srv KciServer) {
	s.RegisterService(&_Kci_serviceDesc, srv)
}

func _Kci_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KciServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kci.Kci/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KciServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kci_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kci.Kci",
	HandlerType: (*KciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "build",
			Handler:    _Kci_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
