// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package kci

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Steps                []*Step  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *BuildRequest) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Step struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Step) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type BuildResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Step                 int32    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BuildResponse) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *BuildResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "kci.BuildRequest")
	proto.RegisterType((*Step)(nil), "kci.Step")
	proto.RegisterType((*BuildResponse)(nil), "kci.BuildResponse")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xba, 0xae, 0x94, 0x03, 0x06, 0x4e, 0x08, 0x59, 0x0c, 0x10, 0x65, 0xca, 0x14,
	0x45, 0x65, 0x60, 0x67, 0x65, 0xa8, 0x64, 0x3e, 0x81, 0x9b, 0x5a, 0x95, 0x55, 0x5a, 0x1b, 0xdf,
	0x65, 0xe0, 0xdb, 0x23, 0xff, 0x19, 0xb2, 0xbd, 0xf7, 0x93, 0xdf, 0xdd, 0xf3, 0x01, 0x5c, 0x8d,
	0xbb, 0x8d, 0x21, 0x7a, 0xf6, 0x28, 0x2e, 0xb3, 0xeb, 0x0f, 0x70, 0xff, 0xb9, 0xb8, 0x9f, 0x93,
	0xb6, 0xbf, 0x8b, 0x25, 0xc6, 0x57, 0x80, 0x68, 0x83, 0x27, 0xc7, 0x3e, 0xfe, 0xa9, 0xa6, 0x6b,
	0x86, 0x56, 0xaf, 0x08, 0xbe, 0x81, 0x24, 0xb6, 0x81, 0xd4, 0xa6, 0x13, 0xc3, 0xdd, 0xbe, 0x1d,
	0x2f, 0xb3, 0x1b, 0xbf, 0xd9, 0x06, 0x5d, 0x78, 0x3f, 0xc1, 0x36, 0x59, 0x7c, 0x02, 0xe9, 0xae,
	0xe6, 0x6c, 0xeb, 0x8c, 0x62, 0x10, 0x61, 0x6b, 0xe2, 0xb9, 0xa4, 0x5b, 0x9d, 0x75, 0x7f, 0x80,
	0x87, 0x5a, 0x81, 0x82, 0xbf, 0x91, 0xc5, 0x67, 0xd8, 0x11, 0x1b, 0x5e, 0xa8, 0x66, 0xab, 0x4b,
	0xe1, 0xb4, 0x43, 0x6d, 0xba, 0x66, 0x90, 0x3a, 0xeb, 0xc4, 0x4e, 0x86, 0x8d, 0x12, 0xf9, 0x65,
	0xd6, 0xfb, 0x0f, 0x10, 0x5f, 0xb3, 0xc3, 0x09, 0xe4, 0x31, 0xcd, 0xc5, 0xc7, 0x5c, 0x72, 0xfd,
	0xcd, 0x17, 0x5c, 0xa3, 0xb2, 0x76, 0x6a, 0x8e, 0xbb, 0x7c, 0x98, 0xf7, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x94, 0x7b, 0x6e, 0xa6, 0x26, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KciClient is the client API for Kci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KciClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Kci_BuildClient, error)
}

type kciClient struct {
	cc *grpc.ClientConn
}

func NewKciClient(cc *grpc.ClientConn) KciClient {
	return &kciClient{cc}
}

func (c *kciClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Kci_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kci_serviceDesc.Streams[0], "/kci.Kci/build", opts...)
	if err != nil {
		return nil, err
	}
	x := &kciBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kci_BuildClient interface {
	Recv() (*BuildResponse, error)
	grpc.ClientStream
}

type kciBuildClient struct {
	grpc.ClientStream
}

func (x *kciBuildClient) Recv() (*BuildResponse, error) {
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KciServer is the server API for Kci service.
type KciServer interface {
	Build(*BuildRequest, Kci_BuildServer) error
}

// UnimplementedKciServer can be embedded to have forward compatible implementations.
type UnimplementedKciServer struct {
}

func (*UnimplementedKciServer) Build(req *BuildRequest, srv Kci_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}

func RegisterKciServer(s *grpc.Server, srv KciServer) {
	s.RegisterService(&_Kci_serviceDesc, srv)
}

func _Kci_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KciServer).Build(m, &kciBuildServer{stream})
}

type Kci_BuildServer interface {
	Send(*BuildResponse) error
	grpc.ServerStream
}

type kciBuildServer struct {
	grpc.ServerStream
}

func (x *kciBuildServer) Send(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Kci_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kci.Kci",
	HandlerType: (*KciServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "build",
			Handler:       _Kci_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "main.proto",
}
