// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package kci

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	Repository             string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Steps                  []*Step  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	RepositorySSHKeySecret string   `protobuf:"bytes,3,opt,name=repositorySSHKeySecret,proto3" json:"repositorySSHKeySecret,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *BuildRequest) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *BuildRequest) GetRepositorySSHKeySecret() string {
	if m != nil {
		return m.RepositorySSHKeySecret
	}
	return ""
}

type Step struct {
	Image                string            `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Args                 []string          `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env                  map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Step) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Step) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

type BuildResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Step                 int32    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BuildResponse) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *BuildResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddSecretRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSecretRequest) Reset()         { *m = AddSecretRequest{} }
func (m *AddSecretRequest) String() string { return proto.CompactTextString(m) }
func (*AddSecretRequest) ProtoMessage()    {}
func (*AddSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *AddSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecretRequest.Unmarshal(m, b)
}
func (m *AddSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecretRequest.Marshal(b, m, deterministic)
}
func (m *AddSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecretRequest.Merge(m, src)
}
func (m *AddSecretRequest) XXX_Size() int {
	return xxx_messageInfo_AddSecretRequest.Size(m)
}
func (m *AddSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecretRequest proto.InternalMessageInfo

func (m *AddSecretRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddSecretRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GenericStatus struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericStatus) Reset()         { *m = GenericStatus{} }
func (m *GenericStatus) String() string { return proto.CompactTextString(m) }
func (*GenericStatus) ProtoMessage()    {}
func (*GenericStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *GenericStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericStatus.Unmarshal(m, b)
}
func (m *GenericStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericStatus.Marshal(b, m, deterministic)
}
func (m *GenericStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericStatus.Merge(m, src)
}
func (m *GenericStatus) XXX_Size() int {
	return xxx_messageInfo_GenericStatus.Size(m)
}
func (m *GenericStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GenericStatus proto.InternalMessageInfo

func (m *GenericStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "kci.BuildRequest")
	proto.RegisterType((*Step)(nil), "kci.Step")
	proto.RegisterMapType((map[string]string)(nil), "kci.Step.EnvEntry")
	proto.RegisterType((*BuildResponse)(nil), "kci.BuildResponse")
	proto.RegisterType((*AddSecretRequest)(nil), "kci.AddSecretRequest")
	proto.RegisterType((*GenericStatus)(nil), "kci.GenericStatus")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x6a, 0xea, 0x40,
	0x10, 0x86, 0x89, 0x6b, 0xe4, 0x64, 0xce, 0x11, 0x3c, 0x43, 0x2b, 0xc1, 0x8b, 0x56, 0x42, 0xa1,
	0x5e, 0x05, 0xb1, 0x20, 0xc5, 0xbb, 0x16, 0xa4, 0x05, 0x2f, 0x0a, 0xc9, 0x13, 0xac, 0xc9, 0x20,
	0x8b, 0x9a, 0xa4, 0xbb, 0x1b, 0xc1, 0x27, 0xe8, 0x5d, 0x9f, 0xb9, 0xec, 0x6e, 0xd2, 0xda, 0x82,
	0xd0, 0xbb, 0x99, 0x7f, 0x77, 0xe7, 0xff, 0xfe, 0x49, 0x00, 0xf6, 0x5c, 0x14, 0x71, 0x25, 0x4b,
	0x5d, 0x22, 0xdb, 0x66, 0x22, 0x7a, 0xf3, 0xe0, 0xdf, 0x63, 0x2d, 0x76, 0x79, 0x42, 0xaf, 0x35,
	0x29, 0x8d, 0x57, 0x00, 0x92, 0xaa, 0x52, 0x09, 0x5d, 0xca, 0x63, 0xe8, 0x8d, 0xbd, 0x49, 0x90,
	0x9c, 0x28, 0x78, 0x0d, 0xbe, 0xd2, 0x54, 0xa9, 0xb0, 0x33, 0x66, 0x93, 0xbf, 0xb3, 0x20, 0xde,
	0x66, 0x22, 0x4e, 0x35, 0x55, 0x89, 0xd3, 0x71, 0x0e, 0xc3, 0xaf, 0xeb, 0x69, 0xfa, 0xbc, 0xa2,
	0x63, 0x4a, 0x99, 0x24, 0x1d, 0x32, 0x3b, 0xec, 0xcc, 0x69, 0xf4, 0xee, 0x41, 0xd7, 0xcc, 0xc1,
	0x0b, 0xf0, 0xc5, 0x9e, 0x6f, 0xa8, 0x31, 0x77, 0x0d, 0x22, 0x74, 0xb9, 0xdc, 0x38, 0xdb, 0x20,
	0xb1, 0x35, 0xde, 0x00, 0xa3, 0xe2, 0x10, 0x32, 0x4b, 0x82, 0x9f, 0x24, 0xf1, 0xb2, 0x38, 0x2c,
	0x0b, 0x2d, 0x8f, 0x89, 0x39, 0x1e, 0xcd, 0xe1, 0x4f, 0x2b, 0xe0, 0x00, 0xd8, 0x96, 0xda, 0x58,
	0xa6, 0x34, 0x6e, 0x07, 0xbe, 0xab, 0x29, 0xec, 0x38, 0x37, 0xdb, 0x2c, 0x3a, 0xf7, 0x5e, 0xf4,
	0x02, 0xfd, 0x66, 0x33, 0xaa, 0x2a, 0x0b, 0x45, 0x38, 0x84, 0x9e, 0xd2, 0x5c, 0xd7, 0xaa, 0x79,
	0xdf, 0x74, 0x06, 0xcd, 0x44, 0xb7, 0x13, 0xfc, 0xc4, 0xd6, 0x46, 0xcb, 0xb9, 0xe6, 0x4d, 0x66,
	0x5b, 0x47, 0x0b, 0x18, 0x3c, 0xe4, 0xb9, 0x8b, 0xdb, 0xae, 0xfb, 0x97, 0x40, 0xd1, 0x2d, 0xf4,
	0x9f, 0xa8, 0x20, 0x29, 0xb2, 0xd4, 0x99, 0x9e, 0x81, 0x99, 0x95, 0xc0, 0x56, 0x99, 0xc0, 0x29,
	0xf8, 0x6b, 0x03, 0x8f, 0xff, 0xed, 0x5a, 0x4e, 0x3f, 0xf1, 0x08, 0x4f, 0x25, 0x97, 0x6d, 0xea,
	0xe1, 0x1c, 0x02, 0xde, 0xd2, 0xe1, 0xa5, 0xbd, 0xf2, 0x93, 0xb6, 0x79, 0xf9, 0x0d, 0x64, 0xdd,
	0xb3, 0x7f, 0xd3, 0xdd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xc6, 0x1b, 0x3f, 0x5b, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KciClient is the client API for Kci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KciClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Kci_BuildClient, error)
	AddSecret(ctx context.Context, in *AddSecretRequest, opts ...grpc.CallOption) (*GenericStatus, error)
}

type kciClient struct {
	cc *grpc.ClientConn
}

func NewKciClient(cc *grpc.ClientConn) KciClient {
	return &kciClient{cc}
}

func (c *kciClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Kci_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kci_serviceDesc.Streams[0], "/kci.Kci/build", opts...)
	if err != nil {
		return nil, err
	}
	x := &kciBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kci_BuildClient interface {
	Recv() (*BuildResponse, error)
	grpc.ClientStream
}

type kciBuildClient struct {
	grpc.ClientStream
}

func (x *kciBuildClient) Recv() (*BuildResponse, error) {
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kciClient) AddSecret(ctx context.Context, in *AddSecretRequest, opts ...grpc.CallOption) (*GenericStatus, error) {
	out := new(GenericStatus)
	err := c.cc.Invoke(ctx, "/kci.Kci/addSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KciServer is the server API for Kci service.
type KciServer interface {
	Build(*BuildRequest, Kci_BuildServer) error
	AddSecret(context.Context, *AddSecretRequest) (*GenericStatus, error)
}

// UnimplementedKciServer can be embedded to have forward compatible implementations.
type UnimplementedKciServer struct {
}

func (*UnimplementedKciServer) Build(req *BuildRequest, srv Kci_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (*UnimplementedKciServer) AddSecret(ctx context.Context, req *AddSecretRequest) (*GenericStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSecret not implemented")
}

func RegisterKciServer(s *grpc.Server, srv KciServer) {
	s.RegisterService(&_Kci_serviceDesc, srv)
}

func _Kci_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KciServer).Build(m, &kciBuildServer{stream})
}

type Kci_BuildServer interface {
	Send(*BuildResponse) error
	grpc.ServerStream
}

type kciBuildServer struct {
	grpc.ServerStream
}

func (x *kciBuildServer) Send(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Kci_AddSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KciServer).AddSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kci.Kci/AddSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KciServer).AddSecret(ctx, req.(*AddSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kci_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kci.Kci",
	HandlerType: (*KciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addSecret",
			Handler:    _Kci_AddSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "build",
			Handler:       _Kci_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "main.proto",
}
